In [0]:
import pandas as pd
import numpy as np


df=pd.read_csv('Participation.csv',header=None)
df

         0    1          2    3     4    5    6        7
0      NaN  lfp    lnnlinc  age  educ  nyc  noc  foreign
1      1.0   no  10.787497    3     8    1    1       no
2      2.0  yes  10.524251  4.5     8    0    1       no
3      3.0   no  10.968578  4.6     9    0    0       no
4      4.0   no  11.104999  3.1    11    2    0       no
5      5.0   no   11.10847  4.4    12    0    2       no
6      6.0  yes  11.028254  4.2    12    0    1       no
7      7.0   no  11.454707  5.1     8    0    0       no
8      8.0  yes  10.490918  3.2     8    0    2       no
9      9.0   no   10.62474  3.9    12    0    0       no
10    10.0   no   10.48642  4.3    11    0    2       no
11    11.0   no  10.660618  4.5    11    0    2       no
12    12.0   no  10.467589    6    12    0    0       no
13    13.0   no  11.229592  3.3    11    2    0       no
14    14.0   no  11.906462  5.6    14    0    0       no
15    15.0   no  11.501562  5.6    11    0    0       no
16    16.0   no  11.293492  4.7    11    0    1       no
17    17.0   no  10.861253    5     8    0    0       no
18    18.0  yes  11.844049  3.9    12    0    0       no
19    19.0   no  11.048627  4.7     8    0    1       no
20    20.0  yes  10.957795  5.3    11    0    0       no
21    21.0   no  10.860134  2.9    19    0    0       no
22    22.0  yes  11.108121  4.6    11    0    1       no
23    23.0   no   10.84862  4.4     8    0    2       no
24    24.0   no  10.482397    2    12    1    0       no
25    25.0  yes   10.48404  5.4     8    0    0       no
26    26.0  yes  10.601204  4.7     8    0    0       no
27    27.0   no  10.540632  2.8     9    2    0       no
28    28.0   no  11.224276  4.7     8    0    1       no
29    29.0  yes  10.841085  4.9    12    0    0       no
..     ...  ...        ...  ...   ...  ...  ...      ...
843  843.0  yes  10.662906  4.6    15    0    1      yes
844  844.0  yes  10.656736  2.6     9    1    0      yes
845  845.0  yes  10.554351  3.1     8    0    2      yes
846  846.0   no  10.500807  4.9     5    0    1      yes
847  847.0   no   10.31735  5.5     5    0    0      yes
848  848.0  yes  10.728559    4     4    0    1      yes
849  849.0   no  10.010429  5.7     6    0    1      yes
850  850.0  yes  10.474912  5.1     5    0    2      yes
851  851.0  yes  11.356841  5.6     3    0    0      yes
852  852.0  yes  10.483732  3.3     2    1    3      yes
853  853.0  yes  10.752502  4.1     5    0    2      yes
854  854.0   no  10.559347  3.2    12    1    0      yes
855  855.0   no  10.215829  2.5    11    1    0      yes
856  856.0  yes  11.574043  4.7    13    0    0      yes
857  857.0  yes  10.806046  3.1    16    2    0      yes
858  858.0   no  10.945839  3.3    14    0    2      yes
859  859.0  yes  10.379906  2.8     5    0    2      yes
860  860.0  yes  10.775556  3.8    11    0    0      yes
861  861.0  yes  10.528899  3.4     9    1    1      yes
862  862.0  yes  10.468534  3.3     6    0    2      yes
863  863.0   no  11.110955  3.5    10    1    1      yes
864  864.0   no  10.471365  5.1     9    0    1      yes
865  865.0   no  10.147503  4.1     5    1    0      yes
866  866.0  yes   10.69323  3.5     9    0    2      yes
867  867.0  yes  10.027595  4.2    14    0    0      yes
868  868.0   no  10.597393  2.4     4    2    1      yes
869  869.0  yes  10.377773  4.8     8    0    0      yes
870  870.0   no   10.13374  2.4     6    2    0      yes
871  871.0  yes  10.932351  4.1    10    0    1      yes
872  872.0   no  11.220691  5.1    10    0    0      yes

[873 rows x 8 columns]

In [0]:
df=df.drop(df.index[0])
del df[0]
df

       1          2    3   4  5  6    7
1     no  10.787497    3   8  1  1   no
2    yes  10.524251  4.5   8  0  1   no
3     no  10.968578  4.6   9  0  0   no
4     no  11.104999  3.1  11  2  0   no
5     no   11.10847  4.4  12  0  2   no
6    yes  11.028254  4.2  12  0  1   no
7     no  11.454707  5.1   8  0  0   no
8    yes  10.490918  3.2   8  0  2   no
9     no   10.62474  3.9  12  0  0   no
10    no   10.48642  4.3  11  0  2   no
11    no  10.660618  4.5  11  0  2   no
12    no  10.467589    6  12  0  0   no
13    no  11.229592  3.3  11  2  0   no
14    no  11.906462  5.6  14  0  0   no
15    no  11.501562  5.6  11  0  0   no
16    no  11.293492  4.7  11  0  1   no
17    no  10.861253    5   8  0  0   no
18   yes  11.844049  3.9  12  0  0   no
19    no  11.048627  4.7   8  0  1   no
20   yes  10.957795  5.3  11  0  0   no
21    no  10.860134  2.9  19  0  0   no
22   yes  11.108121  4.6  11  0  1   no
23    no   10.84862  4.4   8  0  2   no
24    no  10.482397    2  12  1  0   no
25   yes   10.48404  5.4   8  0  0   no
26   yes  10.601204  4.7   8  0  0   no
27    no  10.540632  2.8   9  2  0   no
28    no  11.224276  4.7   8  0  1   no
29   yes  10.841085  4.9  12  0  0   no
30    no  10.566288    3  11  0  1   no
..   ...        ...  ...  .. .. ..  ...
843  yes  10.662906  4.6  15  0  1  yes
844  yes  10.656736  2.6   9  1  0  yes
845  yes  10.554351  3.1   8  0  2  yes
846   no  10.500807  4.9   5  0  1  yes
847   no   10.31735  5.5   5  0  0  yes
848  yes  10.728559    4   4  0  1  yes
849   no  10.010429  5.7   6  0  1  yes
850  yes  10.474912  5.1   5  0  2  yes
851  yes  11.356841  5.6   3  0  0  yes
852  yes  10.483732  3.3   2  1  3  yes
853  yes  10.752502  4.1   5  0  2  yes
854   no  10.559347  3.2  12  1  0  yes
855   no  10.215829  2.5  11  1  0  yes
856  yes  11.574043  4.7  13  0  0  yes
857  yes  10.806046  3.1  16  2  0  yes
858   no  10.945839  3.3  14  0  2  yes
859  yes  10.379906  2.8   5  0  2  yes
860  yes  10.775556  3.8  11  0  0  yes
861  yes  10.528899  3.4   9  1  1  yes
862  yes  10.468534  3.3   6  0  2  yes
863   no  11.110955  3.5  10  1  1  yes
864   no  10.471365  5.1   9  0  1  yes
865   no  10.147503  4.1   5  1  0  yes
866  yes   10.69323  3.5   9  0  2  yes
867  yes  10.027595  4.2  14  0  0  yes
868   no  10.597393  2.4   4  2  1  yes
869  yes  10.377773  4.8   8  0  0  yes
870   no   10.13374  2.4   6  2  0  yes
871  yes  10.932351  4.1  10  0  1  yes
872   no  11.220691  5.1  10  0  0  yes

[872 rows x 7 columns]

In [0]:
X=df.shape[0]
Y=df.shape[1]

In [0]:
df.iloc[:X,0:1]=df.iloc[:X,0:1].replace("yes","1")
df.iloc[:X,0:1]=df.iloc[:X,0:1].replace("no","0")
df.iloc[:X,6:7]=df.iloc[:X,6:7].replace("yes","1")
df.iloc[:X,6:7]=df.iloc[:X,6:7].replace("no","0")
df

     1          2    3   4  5  6  7
1    0  10.787497    3   8  1  1  0
2    1  10.524251  4.5   8  0  1  0
3    0  10.968578  4.6   9  0  0  0
4    0  11.104999  3.1  11  2  0  0
5    0   11.10847  4.4  12  0  2  0
6    1  11.028254  4.2  12  0  1  0
7    0  11.454707  5.1   8  0  0  0
8    1  10.490918  3.2   8  0  2  0
9    0   10.62474  3.9  12  0  0  0
10   0   10.48642  4.3  11  0  2  0
11   0  10.660618  4.5  11  0  2  0
12   0  10.467589    6  12  0  0  0
13   0  11.229592  3.3  11  2  0  0
14   0  11.906462  5.6  14  0  0  0
15   0  11.501562  5.6  11  0  0  0
16   0  11.293492  4.7  11  0  1  0
17   0  10.861253    5   8  0  0  0
18   1  11.844049  3.9  12  0  0  0
19   0  11.048627  4.7   8  0  1  0
20   1  10.957795  5.3  11  0  0  0
21   0  10.860134  2.9  19  0  0  0
22   1  11.108121  4.6  11  0  1  0
23   0   10.84862  4.4   8  0  2  0
24   0  10.482397    2  12  1  0  0
25   1   10.48404  5.4   8  0  0  0
26   1  10.601204  4.7   8  0  0  0
27   0  10.540632  2.8   9  2  0  0
28   0  11.224276  4.7   8  0  1  0
29   1  10.841085  4.9  12  0  0  0
30   0  10.566288    3  11  0  1  0
..  ..        ...  ...  .. .. .. ..
843  1  10.662906  4.6  15  0  1  1
844  1  10.656736  2.6   9  1  0  1
845  1  10.554351  3.1   8  0  2  1
846  0  10.500807  4.9   5  0  1  1
847  0   10.31735  5.5   5  0  0  1
848  1  10.728559    4   4  0  1  1
849  0  10.010429  5.7   6  0  1  1
850  1  10.474912  5.1   5  0  2  1
851  1  11.356841  5.6   3  0  0  1
852  1  10.483732  3.3   2  1  3  1
853  1  10.752502  4.1   5  0  2  1
854  0  10.559347  3.2  12  1  0  1
855  0  10.215829  2.5  11  1  0  1
856  1  11.574043  4.7  13  0  0  1
857  1  10.806046  3.1  16  2  0  1
858  0  10.945839  3.3  14  0  2  1
859  1  10.379906  2.8   5  0  2  1
860  1  10.775556  3.8  11  0  0  1
861  1  10.528899  3.4   9  1  1  1
862  1  10.468534  3.3   6  0  2  1
863  0  11.110955  3.5  10  1  1  1
864  0  10.471365  5.1   9  0  1  1
865  0  10.147503  4.1   5  1  0  1
866  1   10.69323  3.5   9  0  2  1
867  1  10.027595  4.2  14  0  0  1
868  0  10.597393  2.4   4  2  1  1
869  1  10.377773  4.8   8  0  0  1
870  0   10.13374  2.4   6  2  0  1
871  1  10.932351  4.1  10  0  1  1
872  0  11.220691  5.1  10  0  0  1

[872 rows x 7 columns]

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[0:X,0:6], df.iloc[0:X,6:7], test_size=0.30)

## CART

In [0]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[159  45]
 [ 26  32]]
              precision    recall  f1-score   support

           0       0.86      0.78      0.82       204
           1       0.42      0.55      0.47        58

    accuracy                           0.73       262
   macro avg       0.64      0.67      0.65       262
weighted avg       0.76      0.73      0.74       262

## ID3

In [0]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion="entropy")
classifier.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[174  30]
 [ 30  28]]
              precision    recall  f1-score   support

           0       0.85      0.85      0.85       204
           1       0.48      0.48      0.48        58

    accuracy                           0.77       262
   macro avg       0.67      0.67      0.67       262
weighted avg       0.77      0.77      0.77       262

## Logistic Regression

In [0]:
from sklearn.linear_model import LogisticRegression
classifier =  LogisticRegression(tol=0.001)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.001, verbose=0,
                   warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[195   9]
 [ 26  32]]
              precision    recall  f1-score   support

           0       0.88      0.96      0.92       204
           1       0.78      0.55      0.65        58

    accuracy                           0.87       262
   macro avg       0.83      0.75      0.78       262
weighted avg       0.86      0.87      0.86       262

##Random Forest

In [0]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100, max_depth=2, random_state=0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[197   7]
 [ 36  22]]
              precision    recall  f1-score   support

           0       0.85      0.97      0.90       204
           1       0.76      0.38      0.51        58

    accuracy                           0.84       262
   macro avg       0.80      0.67      0.70       262
weighted avg       0.83      0.84      0.81       262

## Neuralnetwork

In [0]:
from sklearn.neural_network import MLPClassifier
classifier = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5, 2), random_state=1)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/multilayer_perceptron.py:921: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(5, 2), learning_rate='constant',
              learning_rate_init=0.001, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=1, shuffle=True, solver='lbfgs', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[204   0]
 [ 58   0]]
              precision    recall  f1-score   support

           0       0.78      1.00      0.88       204
           1       0.00      0.00      0.00        58

    accuracy                           0.78       262
   macro avg       0.39      0.50      0.44       262
weighted avg       0.61      0.78      0.68       262

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

## Perceptron

In [0]:
from sklearn.linear_model import Perceptron
classifier =Perceptron(tol=1e-3, random_state=0)
classifier.fit(X_train, y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=1.0,
           fit_intercept=True, max_iter=1000, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=0, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [0]:
y_pred = classifier.predict(X_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[202   2]
 [ 52   6]]
              precision    recall  f1-score   support

           0       0.80      0.99      0.88       204
           1       0.75      0.10      0.18        58

    accuracy                           0.79       262
   macro avg       0.77      0.55      0.53       262
weighted avg       0.79      0.79      0.73       262

In [2]:
df.shape

NameError: ignored